name: Test Chrome for Stooq

on:
  workflow_dispatch:  # Allows manual trigger


jobs: 
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Matches your local Python version

      - name: Install dependencies
        run: |
    
          pip install --no-cache-dir pandas numpy requests beautifulsoup4 selenium webdriver-manager google-api-python-client jupyter papermill
      

      - name: Debug Chrome and ChromeDriver
        run: |
          which google-chrome
          google-chrome --version
          which chromedriver
          chromedriver --version

      - name: Create chrome data directory
        run: |
          mkdir -p /tmp/chrome_test_data

      - name: Run Minimal Selenium Test
        run: |
          python <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from webdriver_manager.chrome import ChromeDriverManager
          from selenium.webdriver.chrome.options import Options

          options = Options()
          options.add_argument('--headless=new')
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-dev-shm-usage')

          try:
              driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
              driver.get("https://www.stooq.pl")
              print("Chrome launched successfully for target site stooq.pl!")
              driver.quit()
          except Exception as e:
              print(f"Error: {e}")
          EOF
  
      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          cat /tmp/credentials.json | head -n 10  # Debug: Print first 10 lines
     
      - name: Validate JSON Format
        run: |
          python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
      
      - name: Check for Chrome processes
        run: |
          ps aux | grep google-chrome
      
      - name: Execute Notebook
        env:
          PATH: /usr/local/bin:$PATH
        run: |
            # Here, use your Python script or notebook, and load credentials
            # python -c "from google.oauth2 import service_account; creds = service_account.Credentials.from_service_account_file('/tmp/credentials.json', scopes=['https://www.googleapis.com/auth/drive'])"
            papermill test-chrome.ipynb output.ipynb

      - name: Upload Output Notebook as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: output.ipynb
