name: Download dane PPE

on:
  schedule:
    # This cron expression runs the workflow once every 24 hours (UTC time)
    - cron: '0 1 * * *'   # This means every day at 1 am (UTC)
  workflow_dispatch:   # This allows the workflow to be triggered manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    

    
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          sudo apt-get install -y libtesseract-dev
          sudo apt-get install -y tesseract-ocr-pol
          sudo apt-get install -y poppler-utils
          pip install --no-cache-dir pyzipper pytesseract pdf2image google-api-python-client opencv-python-headless pandas
          
      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          
     
      - name: Validate JSON Format
        run: |
              python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
     
      - name: Execute Python Script
        
        env:
          ZIP_URL: ${{ secrets.ZIP_URL }} 
          ZIP_PASSWORD : ${{ secrets.ZIP_PASSWORD }} 
          FOLDER_NAME : ${{ secrets.FOLDER_NAME }}
          INT_FILE_NAME : ${{ secrets.INT_FILE_NAME }}
        run: |
          # Here, use your Python script or notebook, and load credentials
          python  Download-ppe-data.py

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-logs
          path: download.log
      

        