name: Download  FI names from Stooq

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "30 0 15 * *"  # Runs monthly on 15th at 0:30 UTC

jobs:
  process_stooq_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Selenium and webdriver_manager
        run: |
          pip install selenium webdriver-manager pandas numpy requests beautifulsoup4 google-api-python-client

      - name: Run Minimal Selenium Test
        run: |
          python <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from webdriver_manager.chrome import ChromeDriverManager
          from selenium.webdriver.chrome.options import Options

          options = Options()
          options.add_argument('--headless=new')
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-dev-shm-usage')

          try:
              driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
              driver.get("https://www.stooq.pl")
              print("Chrome launched successfully  for target site stooq.pl!!")
              driver.quit()
          except Exception as e:
              print(f"Error: {e}")
          EOF

      - name: Verify Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          
     
      - name: Validate JSON Format
        run: |
          python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
      
      - name: Set range of indexes to run
        env:
          MIN_INDEX: 1000 
          MAX_INDEX: 1500 

          
      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb
      - name: Run Xvfb
        run: |
          xvfb-run --server-args="-screen 0 1280x720x24" python Download-nazwy-FI.py
          
      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-logs
          path: download.log