name: Download and analyse FI from Stooq

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midn UTC

jobs:
  process_stooq_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python deps
        run: |
          pip install  pandas numpy requests  google-api-python-client

      
      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          
     
      - name: Validate JSON Format
        run: |
          python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
          
      - name: Set range of indexes to run
        env:
          MIN_INDEX: 1000 
          MAX_INDEX: 1500 

      - name: Run Python script
        run: |
          python Download-oceny-FI.py
      
      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-logs
          path: download.log
