name: Test strategii single asset - optional robustness check Monte Carlo

on:
  workflow_dispatch:  # Allows manual trigger
 # schedule: ONLY MANUAL
 #   - cron: "0 0 * * *"  # Runs daily at midn UTC

jobs: 
  process_stooq_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     # ------------------------------------------------------------------
      # 2. Python setup
      # ------------------------------------------------------------------
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"
          cache-dependency-path: current_development/requirements.txt

      # ------------------------------------------------------------------
      # 3. Install dependencies
      # ------------------------------------------------------------------
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r current_development/requirements.txt

      
      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          
     
      - name: Validate JSON Format
        run: |
          python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
          
   

      - name: run Python script
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          
          FOLDER_NAME: ${{ secrets.FOLDER_NAME }} 
          
        run: |
          python current_development/asset_config_sweep.py --assets MWIG40TR  --mode full --windows "[(8,2)]" --bootstrap --stopmode fixed
      

      
      - name: Upload log file and chart as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-logs
          path: |
            StratRun.log
            single_asset_equity.png
          retention-days: 30

