name: Run Colab Notebook with Google API Authentication

on:
  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          sudo apt-get install -y libtesseract-dev
          sudo apt-get install -y tesseract-ocr-pol
          sudo apt-get install -y poppler-utils
          pip install pyzipper
          pip install pytesseract
          pip install pdf2image
          pip install google-api-python-client

     - name: Set up Google Credentials
        run: |
        # Write the Google credentials to a file using printf for multiline support
        printf "%s" "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/credentials.json

        # Verify that the file looks correct (printing the first few lines)
        cat /tmp/credentials.json | head -n 20  # Adjust n to control how many lines to print

      - name: Execute Notebook
        run: |
          # Here, use your Python script or notebook, and load credentials
          python -c "from google.oauth2 import service_account; creds = service_account.Credentials.from_service_account_file('/tmp/credentials.json', scopes=['https://www.googleapis.com/auth/drive'])"
          zip_password="${{ secrets.ZIP_PASSWORD }}"
          zip_url="${{ secrets.ZIP_URL }}"
          papermill download_extract.ipynb output.ipynb

      - name: Upload Output Notebook as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: output.ipynb
